_target_: src.models.vit_module.ViTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min

net:
  _target_: src.models.components.custom_vit.ViT
  model_name: vit-b16-224-in21k
  num_classes: 77

rotation_weight: 1.0

# compile model for faster training with pytorch 2.0
compile: false
